"""empty message

Revision ID: f5f1dc79d218
Revises: 
Create Date: 2019-06-10 14:35:55.298940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f1dc79d218'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caseNo', sa.Integer(), nullable=False),
    sa.Column('testcasename', sa.String(length=256), nullable=False),
    sa.Column('precondition', sa.String(length=256), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('logicalresult', sa.Text(), nullable=True),
    sa.Column('databaseresult', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('lastmodifier', sa.Integer(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('modifytime', sa.DateTime(), nullable=True),
    sa.Column('submodule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lastmodifier'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submodule_id'], ['testcasesubmodule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testcase')
    # ### end Alembic commands ###
